# Generated by Django 4.1.7 on 2023-03-26 05:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Текст')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('featured_image', models.ImageField(blank=True, default='def.png', null=True, upload_to='', verbose_name='Изображение')),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка')),
                ('sourse_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка')),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Позитивные голоса')),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество голосов')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('tags', models.ManyToManyField(blank=True, to='projects.tag')),
            ],
            options={
                'ordering': ['-vote_ratio', '-vote_total', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True, verbose_name='Отзыв')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('owner', 'project')},
            },
        ),
    ]
